import type { Metadata } from 'next';
import EmbedGenerator from '@/components/tools/EmbedGenerator';
import WebSiteSchema from '@/components/seo/WebSiteSchema';
import BreadcrumbSchema from '@/components/seo/BreadcrumbSchema';
import FaqSchema from '@/components/seo/FaqSchema';
import SoftwareAppSchema from '@/components/seo/SoftwareAppSchema';
import { seoConfig } from '@/config/seo';

export const metadata: Metadata = {
  title: 'Discord Visual Embed Generator – Webhook Builder',
  description:
    'Design custom Discord embeds visually with our live editor. Generate JSON webhook code, Discord.js builders, and Discord.py commands instantly.',
  keywords: [
    'discord embed generator',
    'discord webhook embed builder',
    'discord embed maker online',
    'webhook embed json creator',
    'how to make a discord webhook embed',
    'visual discord embed builder',
  ],
  alternates: {
    canonical: `${seoConfig.baseUrl}/tools/discord-embed-generator/`,
    languages: {
      'en-US': `${seoConfig.baseUrl}/tools/discord-embed-generator/`,
      'en': `${seoConfig.baseUrl}/tools/discord-embed-generator/`,
    },
  },
  openGraph: {
    title: 'Discord Visual Embed Generator – Webhook Builder',
    description:
      'The best free online tool to build Discord embeds. Customize colors, authors, fields, footer text, and instantly copy Webhook JSON or bot code.',
    url: `${seoConfig.baseUrl}/tools/discord-embed-generator/`,
    type: 'website',
    locale: 'en_US',
    images: [{ url: seoConfig.defaultOgImage, width: 1200, height: 630, alt: 'Discord Embed Generator' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Discord Visual Embed Generator – Webhook Builder',
    description:
      'Design Discord embeds visually with a real-time dark mode preview. Free Webhook generator.',
    site: seoConfig.twitterHandle,
  },
};

const faqItems = [
  {
    question: 'What is a Discord embed?',
    answer:
      'A Discord embed is a rich-media message formatting box with colored sidebars, authors, headers, lists, custom fields, footers, and thumbnails. They are sent via Webhooks or Bots to present formatted data.',
  },
  {
    question: 'How do I use a Discord embed generator?',
    answer:
      'Fill out our visual form fields (title, description, sidebar color, authors, thumbnail URLs, and custom fields) and see a live simulation of what it looks like on Discord. Then copy the generated Webhook JSON code and paste it into your webhook client.',
  },
  {
    question: 'How do I send an embed with a Discord Webhook?',
    answer:
      'Create a webhook in your Discord channel settings, copy the webhook URL, and use our Discord Webhook Sender tool or script to POST the JSON payload generated by this tool directly to your URL.',
  },
  {
    question: 'Does this visual builder support discord.js and discord.py?',
    answer:
      'Yes, our generator provides automated code formats for both Discord.js (v14) and Discord.py, making it a great assistant tool for bot developers.',
  },
];

const PAGE_URL = `${seoConfig.baseUrl}/tools/discord-embed-generator/`;

export default function EmbedGeneratorPage() {
  return (
    <>
      <WebSiteSchema />
      <SoftwareAppSchema
        name="Discord Visual Embed Generator"
        description="Free visual builder to design Discord embeds, preview in dark mode, and export to Webhook JSON, Discord.js, or Discord.py."
        url={PAGE_URL}
        applicationCategory="DeveloperApplication"
      />
      <BreadcrumbSchema
        items={[
          { name: 'Home',  href: `${seoConfig.baseUrl}/` },
          { name: 'Tools', href: `${seoConfig.baseUrl}/tools/` },
          { name: 'Discord Visual Embed Generator', href: PAGE_URL },
        ]}
      />
      <FaqSchema items={faqItems} />

      <div className="max-w-6xl mx-auto px-4 py-8">
        {/* H1 */}
        <header className="mb-8 text-center max-w-3xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold text-[#1a1d2e] mb-3">
            Discord Visual Embed Generator
          </h1>
          <p className="text-lg text-[#5b6282] leading-relaxed">
            Create high-fidelity Discord rich embeds visually. Customize titles, descriptions, theme colors, author headers, and custom tables with a <strong className="text-[#1a1d2e]">live dark mode simulation</strong>. Copy Webhook JSON or bot code in one click.
          </p>
        </header>

        {/* Main interactive tool */}
        <main className="mb-16">
          <EmbedGenerator />
        </main>

        <hr className="border-[#E3E6F0] mb-12" />

        {/* Informative SEO Article */}
        <article className="prose prose-lg max-w-3xl mx-auto text-[#5b6282] space-y-6">
          <h2 className="text-2xl font-bold text-[#1a1d2e]">
            Complete Guide: How to Make a Discord Embed Online
          </h2>
          <p>
            Discord embeds are the professional way to present information inside any Discord channel. Unlike plain text messages, a <strong>Discord embed</strong> displays a rich card with a colored left border, a structured title, description body, fields, thumbnail image, footer, and author header. Server owners, community managers, and bot developers use them every day for announcements, logs, moderation alerts, event details, and more.
          </p>
          <p>
            Our free <strong>Discord Visual Embed Generator</strong> lets you design embeds without writing a single line of JSON or code. Simply fill in the form fields, preview the result in a real-time dark-mode Discord client simulator, and copy the output in seconds.
          </p>

          <h3 className="text-xl font-bold text-[#1a1d2e] pt-2">Understanding Every Discord Embed Field</h3>
          <p>
            Before using a <strong>discord webhook embed builder</strong>, it helps to know what each component does. Here is a complete breakdown of every field available in a Discord embed:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Color (Sidebar):</strong> A hex color code that sets the left accent border. Use brand colors or status colors (green for success, red for errors, yellow for warnings) to make embeds immediately scannable.</li>
            <li><strong>Author:</strong> Displayed at the very top of the embed above the title. It can include a small icon image URL and a hyperlink perfect for crediting a bot or data source.</li>
            <li><strong>Title:</strong> The main headline of the embed. It can optionally link to an external URL, making it clickable in the Discord client.</li>
            <li><strong>Description:</strong> The body of your embed. Supports Discord markdown formatting including bold, italics, code blocks, bullet lists, and more. This is where most of your content lives.</li>
            <li><strong>Fields:</strong> Key-value pairs of information displayed below the description. Fields can be set to &quot;inline&quot; so they appear side by side, creating a clean grid layout ideal for displaying stats, prices, or specifications.</li>
            <li><strong>Thumbnail:</strong> A small square image shown in the top-right corner. Often used for profile pictures, item icons, or mini logos.</li>
            <li><strong>Image:</strong> A large wide image displayed below the fields. Use this for screenshots, charts, maps, or promotional banners.</li>
            <li><strong>Footer:</strong> Text and optional icon shown at the bottom of the embed. Commonly used for timestamps, version numbers, or source credits.</li>
            <li><strong>Timestamp:</strong> An ISO 8601 date/time string that Discord automatically renders in the local timezone of each viewer similar to how <a href="/tools/discord-timestamp-generator/" className="text-[#5865F2] font-bold hover:underline">Discord timestamps</a> work in chat.</li>
          </ul>

          <h3 className="text-xl font-bold text-[#1a1d2e] pt-4">How to Send a Discord Webhook Embed</h3>
          <p>
            Sending an embed via a <strong>Discord webhook</strong> is a three-step process. First, create a webhook in your server channel: go to <em>Channel Settings → Integrations → Webhooks → New Webhook</em>. Copy the webhook URL.
          </p>
          <p>
            Second, use our <strong>discord embed maker online</strong> to build the payload. Our export tab gives you a ready-to-use JSON body that matches the Discord webhook API format exactly. Third, send the JSON payload to the webhook URL using any HTTP client. The quickest way is our built-in <a href="/tools/discord-webhook-sender/" className="text-[#5865F2] font-bold hover:underline">Discord Webhook Sender tool</a> just paste the URL and JSON and hit Send.
          </p>
          <p>
            For automated systems, you can also send it with <code>curl</code>:
          </p>
          <div className="bg-[#1e1f22] rounded-lg p-4 font-mono text-sm text-[#a9b7d0] overflow-x-auto">
            <span className="text-[#98c379]">curl</span> -H <span className="text-[#e5c07b]">&quot;Content-Type: application/json&quot;</span> -d @payload.json YOUR_WEBHOOK_URL
          </div>

          <h3 className="text-xl font-bold text-[#1a1d2e] pt-4">Using Embeds in Discord.js and Discord.py Bots</h3>
          <p>
            Bot developers can use the generated embed data as a reference. In <strong>Discord.js v14</strong>, you create embeds using the <code>EmbedBuilder</code> class. Our generator&apos;s &quot;Discord.js&quot; export tab automatically constructs this boilerplate for you so you can paste it directly into your bot&apos;s handler file.
          </p>
          <p>
            For <strong>Discord.py</strong> developers, our &quot;Discord.py&quot; tab outputs a <code>discord.Embed()</code> constructor call with all your configured properties pre-filled. This saves significant development time when designing bot notification messages, moderation alerts, or automated status reports.
          </p>

          <h3 className="text-xl font-bold text-[#1a1d2e] pt-4">Best Practices for Discord Embeds</h3>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Keep descriptions under 4096 characters</strong> this is Discord&apos;s hard limit for embed descriptions.</li>
            <li><strong>Limit embeds per message to 10</strong> though most use cases only need one or two per message.</li>
            <li><strong>Use inline fields in groups of 3</strong> Discord renders inline fields in rows of three, so grouping them accordingly creates the cleanest visual layout.</li>
            <li><strong>Use HTTPS for all image URLs</strong> Discord will not load images from non-secure HTTP URLs.</li>
            <li><strong>Avoid all-caps titles</strong> they can feel aggressive. Use sentence case for professional server communications.</li>
          </ul>
          <p>
            Whether you are building a status dashboard, posting game announcements, or automating moderation logs, our <strong>Discord embed generator</strong> is the fastest way to go from idea to finished embed. Need to test the output? Pair it with our <a href="/tools/discord-webhook-sender/" className="text-[#5865F2] font-bold hover:underline">Webhook Sender</a> for a complete end-to-end workflow.
          </p>
        </article>

        {/* FAQs */}
        <section aria-labelledby="faq-heading" className="max-w-3xl mx-auto mt-16">
          <h2 id="faq-heading" className="text-2xl font-bold text-[#1a1d2e] mb-6 text-center">
            Frequently Asked Questions
          </h2>
          <div className="space-y-2">
            {faqItems.map((faq, i) => (
              <details key={i} className="rounded-lg bg-white border border-[#E3E6F0]">
                <summary className="px-4 py-3 font-medium text-[#1a1d2e] text-base cursor-pointer list-none flex justify-between items-center gap-2">
                  <span>{faq.question}</span>
                  <span className="text-[#5865F2] shrink-0 text-xl leading-none" aria-hidden="true">+</span>
                </summary>
                <p className="px-4 pb-4 pt-1 text-[#5b6282] text-base leading-relaxed">{faq.answer}</p>
              </details>
            ))}
          </div>
        </section>
      </div>
    </>
  );
}
