import type { Metadata } from 'next';
import PageSchema from '@/components/seo/PageSchema';
import VisibleFAQ from '@/components/seo/VisibleFAQ';
import QRCodeGenerator from '@/components/tools/QRCodeGenerator';
import { seoConfig } from '@/config/seo';

const faqItems = [
  {
    question: 'What is a QR code?',
    answer: 'A QR code (Quick Response code) is a two-dimensional barcode that can store various types of data, such as URLs, text, and contact information.',
  },
  {
    question: 'What is error correction in QR codes?',
    answer: 'Error correction allows QR codes to be scanned even if part of the code is damaged or obscured. Higher levels of error correction make the QR code more reliable but also larger.',
  },
  {
    question: 'Can I use the generated QR codes commercially?',
    answer: 'Yes! All QR codes generated by our tool are free to use for any purpose, including commercial use.',
  },
];

export const metadata: Metadata = {
  title: 'QR Code Generator | Free Custom QR Code Maker',
  description: 'Free QR code generator to create custom QR codes for URLs, text, emails, and more instantly. The best QR code maker for businesses and personal use.',
  keywords: ['qr code generator', 'qr code maker', 'free qr code generator', 'create qr code', 'qr code generator online', 'custom qr code'],
  alternates: { canonical: `${seoConfig.baseUrl}/tools/qr-code-generator/` },
};

const PAGE_URL = `${seoConfig.baseUrl}/tools/qr-code-generator/`;

export default function QRCodeGeneratorPage() {
  return (
    <>
      <PageSchema
        faqItems={faqItems}
        softwareApp={{
          name: 'QR Code Generator',
          description: 'Free QR code generator to create custom QR codes instantly.',
          url: PAGE_URL,
        }}
        breadcrumbs={[
          { name: 'Home', href: `${seoConfig.baseUrl}/` },
          { name: 'Tools', href: `${seoConfig.baseUrl}/tools/` },
          { name: 'QR Code Generator', href: PAGE_URL },
        ]}
      />

      <div className="max-w-5xl mx-auto px-4 py-8">
        <header className="mb-10 text-center space-y-4">
          <h1 className="text-4xl font-extrabold text-[#1a1d2e] leading-tight">
            Free QR Code Generator
          </h1>
          <p className="text-xl text-[#5b6282] max-w-3xl mx-auto">
            Create custom QR codes for URLs, text, emails, phone numbers, and more instantly with our free QR code generator.
          </p>
        </header>

        <section className="mb-12">
          <QRCodeGenerator />
        </section>

        <article className="prose prose-lg max-w-none text-[#5b6282] bg-white p-8 md:p-12 rounded-2xl border border-[#E3E6F0] shadow-sm">
          <h2>How to Use Our QR Code Generator</h2>
          <p>
            Our QR code generator makes it easy to create custom QR codes for any purpose. Simply enter your text or URL, customize the size and error correction level, and download your QR code.
          </p>

          <h3>Uses for QR Codes</h3>
          <ul>
            <li>Linking to websites</li>
            <li>Sharing contact information</li>
            <li>Connecting to Wi-Fi networks</li>
            <li>Displaying product information</li>
            <li>Marketing and advertising campaigns</li>
          </ul>
        </article>

        <VisibleFAQ items={faqItems} />
      </div>
    </>
  );
}
